-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 07:47:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assignment1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assignment1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assignment1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assignment1` ;

-- -----------------------------------------------------
-- Table `assignment1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignment1`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1`.`application` (
  `app_id` INT NOT NULL,
  `Rating` VARCHAR(45) NULL DEFAULT NULL,
  `Category_category_id` INT NOT NULL,
  `AppName` VARCHAR(45) NULL DEFAULT NULL,
  `Reviews` VARCHAR(45) NULL DEFAULT NULL,
  `TotalInstall` VARCHAR(45) NULL DEFAULT NULL,
  `Size` VARCHAR(45) NULL DEFAULT NULL,
  `Last Updated` VARCHAR(45) NULL DEFAULT NULL,
  `Current Ver` VARCHAR(45) NULL DEFAULT NULL,
  `Android Ver` VARCHAR(45) NULL DEFAULT NULL,
  `ge` VARCHAR(45) NULL,
  `idGenre` INT NULL,
  PRIMARY KEY (`app_id`),
  INDEX `fk_Application_Category1_idx` (`Category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Application_Cat1`
    FOREIGN KEY (`Category_category_id`)
    REFERENCES `assignment1`.`category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignment1`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1`.`review` (
  `review_id` INT NOT NULL,
  `Application_app_id` INT NOT NULL,
  `Translated_Review` TEXT NULL DEFAULT NULL,
  `AppName` VARCHAR(45) NULL DEFAULT NULL,
  `Sentiment` VARCHAR(45) NULL DEFAULT NULL,
  `Sentiment_Subjectivity` VARCHAR(45) NULL DEFAULT NULL,
  `Sentiment_Polarity` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_Reviews_Application_idx` (`Application_app_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_Application`
    FOREIGN KEY (`Application_app_id`)
    REFERENCES `assignment1`.`application` (`app_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assignment1`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1`.`Genre` (
  `idGenre` INT NOT NULL,
  `Genre_name` VARCHAR(45) NULL,
  `Genrecol` VARCHAR(45) NULL,
  `app_id` INT NULL,
  `Genrecol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignment1`.`temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assignment1`.`temp` (
  `genre_id` INT NULL,
  `app_id` INT NULL,
  INDEX `fk_gid_idx` (`genre_id` ASC, `app_id` ASC) VISIBLE,
  CONSTRAINT `fk_gid`
    FOREIGN KEY (`genre_id` , `app_id`)
    REFERENCES `assignment1`.`Genre` (`idGenre` , `idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appid`
    FOREIGN KEY (`genre_id` , `app_id`)
    REFERENCES `assignment1`.`application` (`app_id` , `app_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
