-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 07:45:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`university` (
  `iduniversity` INT NOT NULL,
  `uaddress` VARCHAR(45) NULL,
  `uname` VARCHAR(45) NULL,
  PRIMARY KEY (`iduniversity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `iddepartment` INT NOT NULL,
  `department_name` VARCHAR(45) NULL,
  `iduniversity` INT NULL,
  PRIMARY KEY (`iddepartment`),
  INDEX `fkk_uni_idx` (`iduniversity` ASC) VISIBLE,
  CONSTRAINT `fkk_uni`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `professor_id` INT NOT NULL,
  `professor_name` VARCHAR(45) NULL,
  `professor_lname` VARCHAR(45) NULL,
  `iddepartment` INT NOT NULL,
  `facultycol` VARCHAR(45) BINARY NULL,
  `facultycol1` VARCHAR(45) BINARY NULL,
  `facultycol2` VARCHAR(45) BINARY NULL,
  `facultycol3` VARCHAR(45) BINARY NULL,
  `facultycol4` VARCHAR(45) BINARY NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_dept_idx` (`iddepartment` ASC) VISIBLE,
  CONSTRAINT `fk_dept`
    FOREIGN KEY (`iddepartment`)
    REFERENCES `mydb`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`programs` (
  `idprograms` INT NOT NULL,
  `program_names` VARCHAR(45) NULL,
  `iddepartment` INT NULL,
  PRIMARY KEY (`idprograms`),
  INDEX `fk_iddep_idx` (`iddepartment` ASC) VISIBLE,
  CONSTRAINT `fk_iddep`
    FOREIGN KEY (`iddepartment`)
    REFERENCES `mydb`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `idstudents` INT NOT NULL,
  `studentname` VARCHAR(45) NULL,
  `iddepartment` INT NULL,
  `iduniversity` INT NULL,
  PRIMARY KEY (`idstudents`),
  INDEX `fk_uni_idx` (`iduniversity` ASC) VISIBLE,
  INDEX `fk_dept_idx` (`iddepartment` ASC) VISIBLE,
  CONSTRAINT `fk_uni`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept`
    FOREIGN KEY (`iddepartment`)
    REFERENCES `mydb`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funding` (
  `idFunding` INT NOT NULL,
  `funding_amount` FLOAT NULL,
  `iduniversity` INT NULL,
  `idstudents` INT NULL,
  PRIMARY KEY (`idFunding`),
  INDEX `fk_uni_idx` (`iduniversity` ASC) VISIBLE,
  INDEX `fk_student_idx` (`idstudents` ASC) VISIBLE,
  CONSTRAINT `fok_uni`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student`
    FOREIGN KEY (`idstudents`)
    REFERENCES `mydb`.`students` (`idstudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auditorium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auditorium` (
  `idAuditorium` INT NOT NULL,
  `auditorium_name` VARCHAR(45) NULL,
  `iduniversity` INT NULL,
  PRIMARY KEY (`idAuditorium`),
  INDEX `fk_uni_idx` (`iduniversity` ASC) VISIBLE,
  CONSTRAINT `fk_univ`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `idEvents` INT NOT NULL,
  `Event_name` VARCHAR(45) NULL,
  `eventlocation` VARCHAR(45) NULL,
  `event_date` DATE NULL,
  `iduniversity` INT NULL,
  `idAuditorium` INT NULL,
  PRIMARY KEY (`idEvents`),
  INDEX `fk_unii_idx` (`iduniversity` ASC) VISIBLE,
  INDEX `fk_audi_idx` (`idAuditorium` ASC) VISIBLE,
  CONSTRAINT `fk_unii`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi`
    FOREIGN KEY (`idAuditorium`)
    REFERENCES `mydb`.`Auditorium` (`idAuditorium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libraries` (
  `idlibraries` INT NOT NULL,
  `library_loc` VARCHAR(45) NULL,
  `library_name` VARCHAR(45) NULL,
  `iduniversity` INT NULL,
  INDEX `fkkk_uni_idx` (`iduniversity` ASC) VISIBLE,
  CONSTRAINT `fkkk_uni`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campuses` (
  `idCampuses` INT NOT NULL,
  `campusname` VARCHAR(45) NULL,
  `iduniversity` INT NULL,
  PRIMARY KEY (`idCampuses`),
  INDEX `fkk_uniii_idx` (`iduniversity` ASC) VISIBLE,
  CONSTRAINT `fkk_uniii`
    FOREIGN KEY (`iduniversity`)
    REFERENCES `mydb`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `idBuildings` INT NOT NULL,
  `Building name` VARCHAR(45) NULL,
  `idCampuses` INT NULL,
  PRIMARY KEY (`idBuildings`),
  INDEX `fk_campus_idx` (`idCampuses` ASC) VISIBLE,
  CONSTRAINT `fk_campus`
    FOREIGN KEY (`idCampuses`)
    REFERENCES `mydb`.`Campuses` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
